import './globals.css'
import type { Metadata } from 'next'
import SBURBHeader from './components/sburb-header'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body>
				<SBURBHeader />
				{children}
			</body>
		</html>
	)
}
